# Etapa 1: Construção
FROM node:22.13 AS builder

WORKDIR /usr/app

# Copia apenas os arquivos essenciais para cache eficiente
COPY package.json package-lock.json ./

# Instala dependências de produção e desenvolvimento
RUN npm install

# Copia todo o código fonte
COPY . .

# Constrói o Next.js
RUN npm run build

# Etapa 2: Servindo o Next.js com Node.js
FROM node:22.13

WORKDIR /usr/app

# Copia apenas os arquivos necessários para rodar em produção
COPY --from=builder /usr/app/package.json ./
COPY --from=builder /usr/app/package-lock.json ./
COPY --from=builder /usr/app/.next ./.next
COPY --from=builder /usr/app/public ./public
COPY --from=builder /usr/app/node_modules ./node_modules

# Instala apenas as dependências de produção
RUN npm install --omit=dev

# Expor a porta do Next.js
EXPOSE 3000

# Iniciar o servidor Next.js no modo produção
CMD ["npm", "run", "start"]
