FROM node:22.13

# Atualiza o linux e instala o SQLite3 no contêiner
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev

# Instala o FFmpeg
RUN apt-get update && \
apt-get install -y ffmpeg && \
apt-get clean && rm -rf /var/lib/apt/lists/*

# Adiciona permissões para o diretório do banco de dados
RUN mkdir -p /usr/server && chmod -R 777 /usr/server

# Define o diretório de trabalho no contêiner
WORKDIR /usr/server

# Copia os arquivos de configuração do Node.js para instalar dependências
COPY package*.json ./

# Copia o restante dos arquivos para o contêiner
COPY . ./

# Instala as dependências do Babel
RUN npm install --save @babel/node @babel/core @babel/cli @babel/preset-env @babel/plugin-transform-async-to-generator @babel/plugin-transform-runtime @babel/runtime

# Instala as dependências
RUN npm ci

# Expõe a porta 3001
EXPOSE 3001

# Comando para rodar o servidor
CMD ["npm", "run", "server"]
