## Remover foto de perfil [/api/account/picture]

### Remover foto de perfil [DELETE]

Deleta a foto de perfil do servidor e a substitui pelas iniciais.

::: note
Limite de acesso: Máxima de 10 tentativas, bloqueio de 120 segundos.
:::

::: note
Protegido pelo middleware `isAuth`.
:::

::: note
Limite máximo de upload: 100mb. Tamanho máximo do arquivo: 4mb.
:::


### **Exemplo usando fetch com formData**
```javascript
const URL = "https://dev-diboaclub.onrender.com";
const TOKEN = "JWT.EXAMPLE.TOKEN";

fetch(URL + "/api/account/picture", {
method: "DELETE",
headers: {
    "authorization": `Bearer ${TOKEN}`,
}})
.then(response => response.json())
.then(data => console.log("Resposta:", data))
.catch(error => console.error("Erro:", error));
```

+ Request Enviar foto de perfil

    + Headers

            Content-Type: application/json
            authorization: Bearer <token>

+ Response 200 (application/json)
        
    + body

            {
                "success": true,
                "message": "Foto de perfil removida.",
                "picture": "LINK.FOTOPERFIL.COM/media/picture/CODIGOFOTO.webp"
            }

+ Response 400 (application/json)
    + Body

            { "success": false, "error": "Erro no upload da imagem."}
            { "success": false, "error": "Erro ao deletar arquivo." }

+ Response 401 (application/json)
    + Body

            { "success": false, "error": "Usuário não autenticado", "logout": true }

+ Response 404 (application/json)
    + Body

            { "error": "Arquivo não encontrado." }
            { "error": "Token não encontrado." }

+ Response 429 (application/json)
    + body

            { "error": "Muitas solicitações, aguarde <<tempo>> segundos" }

+ Response 500 (application/json)
    + Body

            { "error": "Erro inesperado." }