// # Group Favorites

// <!-- include(./getFavorites.apib) -->
// <!-- include(./postFavorites.apib) -->


# Group Complaints

<!-- include(./getComplaint.apib) -->
<!-- include(./postComplaint.apib) -->
// <!-- include(./deleteComplaint.apib) -->
