# Group Provider

<!-- include(./get-search.apib) -->
<!-- include(./get-provider.apib) -->
<!-- include(./get-provider-byid.apib) -->
<!-- include(./post-file.apib) -->
<!-- include(./delete-file.apib) -->

